---
name: 拉汀那
markdown: redcarpet

redcarpet:
  extensions: ["tables"]
 
title: Savor d'Isavano
email: newelevenken@163.com
description: > # this means to ignore newlines until "baseurl:"
  Languages, Ratina
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.ratina.org" # the base hostname & protocol for your site
permalink: /blog/:year/:month/:day/:title
github_username: KenetJervet

collections:
  lang_event:
    - a